### ISSUE TITLE
自己整理的笔记-大家可以看看

### ISSUE THREAD

**Issue by happybear1015** [Chinese-NLP-book/rasa_chinese_book_code#21]
[内容已删除]

**Comment by howl-anderson** [comment]
感谢你对我们项目的关注。然而，我们项目的issue区仅用于报告bug、提出功能请求或讨论与项目相关的问题。请注意，项目不允许任何形式的广告或推广。

为了确保社区的安全和秩序，我们会立即关闭此issue。同时提醒所有社区成员，请避免下载和使用未经验证的资料，这可能存在安全风险。
