### ISSUE TITLE
第五章启动问题

### ISSUE THREAD

**Issue by xl876075921** [Chinese-NLP-book/rasa_chinese_book_code#3]
环境是windows10,启动动作服务器时遇到如下问题
 无法将“SENIVERSE_KEY=xxx”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。

**Comment by happybear1015** [comment]
请问解决了吗？我也遇到同样的问题~

**Comment by happybear1015** [comment]
代替wind大佬回复一下：社区里之前有人遇到过..其实Windows平台不需要输入这个环境变量..你在代码里将这个值赋值下就可以了.

**Comment by happybear1015** [comment]
具体修改的地方在：weather.py，将api中填写 私钥 就可以了。

**Comment by howl-anderson** [comment]
Hi All, 本 issue 所列问题已在 https://github.com/Chinese-NLP-book/rasa_chinese_book_code/commit/e59cec84de14fa61cdfb08893cbea125438de8a7 中修复，感谢支持！
