### ISSUE TITLE
第五章cities.yml问题

### ISSUE THREAD

**Issue by Kac001** [Chinese-NLP-book/rasa_chinese_book_code#5]
nlu:
  - lookup: cities 
 应该改address,与nlu文件中的实体类型一致

**Comment by chcodex** [comment]
我好像也发现这个问题了

**Comment by howl-anderson** [comment]
Hi, Lookup table 的名字和 intent 和 entity 名字之间无需存在对应关系。

> The name of a regex in this case is a human readable description. It can help you remember what a regex is used for, and it is the title of the corresponding pattern feature. It does not have to match any intent or entity name. 

详见文档 https://rasa.com/docs/rasa/nlu-training-data#lookup-tables 和 https://rasa.com/docs/rasa/nlu-training-data#regular-expressions-for-intent-classification 。

如果对相关机制的工作原理非常感兴趣的，可以阅读 Rasa 代码，可以更深入的理解 `It only provides a feature that the intent classifier will use to learn patterns for intent classification.`
