### ISSUE TITLE
Templete defined not found

### ISSUE THREAD

**Issue by kolapapa** [Chinese-NLP-book/rasa_chinese_book_code#6]
https://github.com/Chinese-NLP-book/rasa_chinese_book_code/blob/cab23b9981ededff45cc2b17463f5541bf8b8568/Chapter05/actions.py#L28

No definition of `templates` found in `domain.yml`.

**Comment by howl-anderson** [comment]
Hi 感谢支持，已经在 https://github.com/Chinese-NLP-book/rasa_chinese_book_code/commit/bf18725eba3c4fb716c8c2bfa4b188b01de7aeee 中修复。
