### ISSUE TITLE
第6章知识图谱相关问题

### ISSUE THREAD

**Issue by jacksonjack001** [Chinese-NLP-book/rasa_chinese_book_code#7]
/Chapter06/neo4j_knowledge_base.py中
`    result = loop.run_until_complete(kb.get_object("singer", "周杰伦"))
    print(result)`

代码报错，看起来是neo4j的匹配语句出问题导致的
query = "MATCH (o:{object_type} {{{key}:{value}}}) RETURN o, ID(o)".format(
            object_type=object_type, key=key_attribute, value=object_identifier
        )
这里得到key和value不知道是哪个出了问题
MATCH (o:Singer {id:周杰伦}) RETURN o, ID(o)

可以帮忙看看怎么修改么？实际运行的pythonweb服务也是报错的

**Comment by ume-technology** [comment]
这个代码其实就是一坨垃圾，幸亏是网上下的pdf的书，这本书的实体书谁买谁上当

**Comment by jacksonjack001** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    有点子书么，共享下？
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                21635029
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年04月10日 14:35
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Chinese-NLP-book/rasa_chinese_book_code] 第6章知识图谱相关问题 (Issue #7)
        
      
    
  
  
这个代码其实就是一坨垃圾，幸亏是网上下的pdf的书，这本书的实体书谁买谁上当

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ume-technology** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 有点子书么，共享下？ 21635029 ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年04月10日 14:35 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [Chinese-NLP-book/rasa_chinese_book_code] 第6章知识图谱相关问题 (Issue #7) 这个代码其实就是一坨垃圾，幸亏是网上下的pdf的书，这本书的实体书谁买谁上当 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>


留邮箱，我发你

**Comment by jacksonjack001** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        ***@***.***，感谢。最近chatgpt大伙，还有人看rasa说明同道中人
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                21635029
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年04月10日 14:55
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Chinese-NLP-book/rasa_chinese_book_code] 第6章知识图谱相关问题 (Issue #7)
        
      
    
  
  

font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 有点子书么，共享下？ 21635029 @.***
…
---- 回复的原邮件 ---- 发件人 @.> 发送日期 2023年04月10日 14:35 收件人 @.> 抄送人 @.> , @.> 主题 Re: [Chinese-NLP-book/rasa_chinese_book_code] 第6章知识图谱相关问题 (Issue #7) 这个代码其实就是一坨垃圾，幸亏是网上下的pdf的书，这本书的实体书谁买谁上当 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

留邮箱，我发你

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ume-technology** [comment]
> 21635029

是这个  21635029@qq.com    邮箱吧。  或者这是我的微信号，newswithspring 方便地话你直接加我微信，我们可以微信讨论，互相贡献自己的工作，这样彼此可能思路会开阔一点。

**Comment by howl-anderson** [comment]
Hi @jacksonjack001 @ume-technology ，
感谢你们对本项目的关注。首先，我们想强调的是，本书的作者团队非常注重代码质量，本书的代码在发布前都是通过了相关的测试的，无论是自动的冒烟测试（参见 Makefile 中的 smoke_test 部分）还是手动的功能测试，因此代码质量在一定程度上做了保障。在不同的部署环境中的可复现，我们也在 windows、mac 和 linux 上做了一些确认。尽管如此，我们依旧无法保证在所有的环境中都能稳定的复现所有功能。如果你们有关于书或代码的具体反馈，我们是非常欢迎的，也会尽量采纳、解决或者解释原因。

同时，我们需要申明的是，我们反对任何盗版行为。盗版行为一方面触犯相关法律，另一方面有着长远的危害：盗版行为不仅不尊重创作者付出的努力，而且会损害正版用户的利益，挫伤原创作者的创作积极性，以及损害整个开源社区的创新能力。因此，请你们停止相关的盗版行为，并删除相关信息。如果确实因为经济原因无法购买正版图书，欢迎通过邮件联系作者，我们非常乐意为你们支付相关的图书购买费用，以鼓励你们购买正版图书。

非常感谢你们的理解和支持。

**Comment by jacksonjack001** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    收到，后面没有跟进了哈，尊重版权，不好意思
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                21635029
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Xiaoquan ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年04月10日 21:54
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Chinese-NLP-book/rasa_chinese_book_code] 第6章知识图谱相关问题 (Issue #7)
        
      
    
  
  
Hi @jacksonjack001 @ume-technology ，
感谢你们对本项目的关注。首先，我们想强调的是，本书的作者团队非常注重代码质量，本书的代码在发布前都是通过了相关的测试的，无论是自动的冒烟测试（参见 Makefile 中的 smoke_test 部分）还是手动的功能测试，因此代码质量在一定程度上做了保障。在不同的部署环境中的可复现，我们也在 windows、mac 和 linux 上做了一些确认。尽管如此，我们依旧无法保证在所有的环境中都能稳定的复现所有功能。如果你们有关于书或代码的具体反馈，我们是非常欢迎的，也会尽量采纳、解决或者解释原因。
同时，我们需要申明的是，我们反对任何盗版行为。盗版行为一方面触犯相关法律，另一方面有着长远的危害：盗版行为不仅不尊重创作者付出的努力，而且会损害正版用户的利益，挫伤原创作者的创作积极性，以及损害整个开源社区的创新能力。因此，请你们停止相关的盗版行为，并删除相关信息。如果确实因为经济原因无法购买正版图书，欢迎通过邮件联系作者，我们非常乐意为你们支付相关的图书购买费用，以鼓励你们购买正版图书。
非常感谢你们的理解和支持。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by howl-anderson** [comment]
@jacksonjack001 感谢您的回应，我们感到非常欣慰！非常感谢您的理解与支持！让我们保持交流，如果我们未能及时回复您的消息，欢迎通过邮件联系我们。

**Comment by ume-technology** [comment]
> Hi @jacksonjack001 @ume-technology ， 感谢你们对本项目的关注。首先，我们想强调的是，本书的作者团队非常注重代码质量，本书的代码在发布前都是通过了相关的测试的，无论是自动的冒烟测试（参见 Makefile 中的 smoke_test 部分）还是手动的功能测试，因此代码质量在一定程度上做了保障。在不同的部署环境中的可复现，我们也在 windows、mac 和 linux 上做了一些确认。尽管如此，我们依旧无法保证在所有的环境中都能稳定的复现所有功能。如果你们有关于书或代码的具体反馈，我们是非常欢迎的，也会尽量采纳、解决或者解释原因。
> 
> 同时，我们需要申明的是，我们反对任何盗版行为。盗版行为一方面触犯相关法律，另一方面有着长远的危害：盗版行为不仅不尊重创作者付出的努力，而且会损害正版用户的利益，挫伤原创作者的创作积极性，以及损害整个开源社区的创新能力。因此，请你们停止相关的盗版行为，并删除相关信息。如果确实因为经济原因无法购买正版图书，欢迎通过邮件联系作者，我们非常乐意为你们支付相关的图书购买费用，以鼓励你们购买正版图书。
> 
> 非常感谢你们的理解和支持。

矫情起来了？  你仔细去看看你的配套代码。一坨奥里给。 各种各样的错误，甚至stories中出现的意图都没配置在domain中，就这还大言不惭做了相关测试？ 你在虚空计算机上做的测试？？？？
